//AUTOGENERATED FILE FROM png2asset
// Conversion args: /flag_padded.png -o /flag_spr.c -sw 8 -sh 16 -spr8x8

#ifndef METASPRITE_flag_spr_H
#define METASPRITE_flag_spr_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define flag_spr_TILE_ORIGIN 0
#define flag_spr_TILE_W 8
#define flag_spr_TILE_H 8
#define flag_spr_WIDTH 8
#define flag_spr_HEIGHT 16
#define flag_spr_TILE_COUNT 2
#define flag_spr_PALETTE_COUNT 1
#define flag_spr_COLORS_PER_PALETTE 4
#define flag_spr_TOTAL_COLORS 4
#define flag_spr_PIVOT_X 4
#define flag_spr_PIVOT_Y 8
#define flag_spr_PIVOT_W 8
#define flag_spr_PIVOT_H 16
extern const metasprite_t* const flag_spr_metasprites[1];

BANKREF_EXTERN(flag_spr)

extern const palette_color_t flag_spr_palettes[4];
extern const uint8_t flag_spr_tiles[32];

#endif
