//AUTOGENERATED FILE FROM png2asset
// Conversion args: /flag_padded.png -o /flag_spr.c -sw 8 -sh 16 -spr8x8

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(flag_spr)

const palette_color_t flag_spr_palettes[4] = {
	RGB8(255,255,255), RGB8(201,255,255), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	};

const uint8_t flag_spr_tiles[32] = {
	0xe0,0x00,0xb8,0x00,0x86,0x00,0xb8,0x00,0xe0,0x00,0x80,0x00,0x80,0x00,0x80,0x00,
	0x80,0x00,0x80,0x00,0x80,0x00,0x80,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
	};

const metasprite_t flag_spr_metasprite0[] = {
	METASPR_ITEM(-8, -4, 0, S_PAL(0)),
	METASPR_ITEM(8, 0, 1, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const flag_spr_metasprites[1] = {
	flag_spr_metasprite0
};
