//AUTOGENERATED FILE FROM png2asset
// Conversion args: /font.png -o /font.c -map -spr8x8 -tile_origin 2 -noflip -max_palettes 1

#ifndef METASPRITE_font_H
#define METASPRITE_font_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_TILE_ORIGIN 2
#define font_TILE_W 8
#define font_TILE_H 8
#define font_WIDTH 664
#define font_HEIGHT 8
#define font_TILE_COUNT 81
#define font_PALETTE_COUNT 1
#define font_COLORS_PER_PALETTE 4
#define font_TOTAL_COLORS 4
#define font_MAP_ATTRIBUTES 0
extern const unsigned char font_map[83];
#define font_map_attributes font_map

BANKREF_EXTERN(font)

extern const palette_color_t font_palettes[4];
extern const uint8_t font_tiles[1296];

#endif
