//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ship.png -o /ship.c -sw 16 -sh 16 -spr8x8

#ifndef METASPRITE_ship_H
#define METASPRITE_ship_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ship_TILE_ORIGIN 0
#define ship_TILE_W 8
#define ship_TILE_H 8
#define ship_WIDTH 16
#define ship_HEIGHT 16
#define ship_TILE_COUNT 16
#define ship_PALETTE_COUNT 1
#define ship_COLORS_PER_PALETTE 4
#define ship_TOTAL_COLORS 4
#define ship_PIVOT_X 8
#define ship_PIVOT_Y 8
#define ship_PIVOT_W 16
#define ship_PIVOT_H 16
extern const metasprite_t* const ship_metasprites[8];

BANKREF_EXTERN(ship)

extern const palette_color_t ship_palettes[4];
extern const uint8_t ship_tiles[256];

#endif
