//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ship2.png -o /ship2.c -sw 16 -sh 16 -spr8x8

#ifndef METASPRITE_ship2_H
#define METASPRITE_ship2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ship2_TILE_ORIGIN 0
#define ship2_TILE_W 8
#define ship2_TILE_H 8
#define ship2_WIDTH 16
#define ship2_HEIGHT 16
#define ship2_TILE_COUNT 16
#define ship2_PALETTE_COUNT 1
#define ship2_COLORS_PER_PALETTE 4
#define ship2_TOTAL_COLORS 4
#define ship2_PIVOT_X 8
#define ship2_PIVOT_Y 8
#define ship2_PIVOT_W 16
#define ship2_PIVOT_H 16
extern const metasprite_t* const ship2_metasprites[8];

BANKREF_EXTERN(ship2)

extern const palette_color_t ship2_palettes[4];
extern const uint8_t ship2_tiles[256];

#endif
